`timescale 1ns/1ps
`include "karaoke_top.sv"

module karaoke_top_tb;

    // --- 1. TB Clock Generation Signals ---
    // Primary clock: 48 MHz (Simulated OSC input)
    logic clk_48mhz_tb;
    parameter CLK_48MHZ_PERIOD = 1_000_000_000 / 48_000_000; // ~20.83 ns
    
    // Divided clocks generated by DUT (received by TB)
    logic clk_1m536mhz; // 1.536 MHz (Audio Domain, driven by DUT)

    // --- 2. DUT Interface Signals ---
    logic pdm_data;
    logic reset_n;

    // DUT Outputs
    logic signed [15:0] audio_sample;
    logic audio_valid;

    logic sck;       // SPI SCK
    logic sdo;       // SPI SDO
    logic cs;        // SPI CS

    // --- 3. Internal TB Signals & Parameters ---
    parameter SIM_LENGTH = 20_000_000; // Increased to 20ms for more samples
    parameter CLK_6MHZ_PERIOD = 1_000_000_000 / 6_000_000; // 166.67 ns

    // PDM/Filter Chain Constants
    localparam real PDM_FREQ = 1_536_000.0;
    localparam real FINAL_OUTPUT_RATE = 16_000.0;
    localparam int FINAL_DECIMATION = 96; // (1.536M / 16k = 96)

    // Sigma-delta modulator state for PDM generation
    real sigma_delta_integrator = 0.0;

    // Variables for Output Monitoring and Verification
    // FIXED: Changed from dynamic queue 'real output_samples[$]' to fixed array 
    // to avoid vsim-4027 error when logging dynamic array types.
    real output_samples[0:4095]; 
    integer output_count = 0;

    // --- 4. Clock Generation (48 MHz) ---
    initial begin
        clk_48mhz_tb = 1'b0;
        forever #(CLK_48MHZ_PERIOD / 2) clk_48mhz_tb = ~clk_48mhz_tb;
    end

    // --- 5. Helper Functions (for PDM/Q15 conversion) ---
    // Converts 16-bit Q15 integer to real number [-1.0, 1.0)
    function real q15_to_real(logic signed [15:0] val);
        return $itor(val) / 32768.0;
    endfunction
    
    // Converts real number [-1.0, 1.0) to 16-bit Q15 integer
    function logic signed [15:0] real_to_q15(real val);
        real clamped;
        clamped = (val > 0.99999) ? 0.99999 : (val < -1.0) ? -1.0 : val;
        return $rtoi(clamped * 32768.0);
    endfunction
    
    // Helper function for absolute value
    function real abs_real(real val);
        return (val < 0.0) ? -val : val;
    endfunction

    // --- 6. PDM Generation Tasks (using clk_1m536mhz) ---

    // PDM generation using first-order sigma-delta modulation
    task generate_pdm_sample(input real analog_val);
        real error;
        
        // Clamp input to [-1, 1]
        if (analog_val > 1.0) analog_val = 1.0;
        if (analog_val < -1.0) analog_val = -1.0;
        
        // First-order sigma-delta
        sigma_delta_integrator = sigma_delta_integrator + analog_val;
        
        if (sigma_delta_integrator >= 0.0) begin
            pdm_data = 1'b1;
            error = 1.0;
        end else begin
            pdm_data = 1'b0;
            error = -1.0;
        end
        
        sigma_delta_integrator = sigma_delta_integrator - error;
        
        @(posedge clk_1m536mhz);
    endtask
    
    // Generate continuous PDM stream (Sine Wave)
    task generate_pdm_tone(input real freq, input int num_output_samples);
        real phase, phase_inc, analog_val;
        int i;
        
        phase = 0.0;
        phase_inc = freq / PDM_FREQ;
        
        // Generate PDM for specified number of final 16kHz output samples
        for (i = 0; i < num_output_samples * FINAL_DECIMATION; i++) begin
            // 0.7 amplitude tone
            analog_val = 0.7 * $sin(2.0 * 3.14159265359 * phase);
            generate_pdm_sample(analog_val);
            
            phase = phase + phase_inc;
            if (phase >= 1.0) phase = phase - 1.0;
        end
    endtask
    
    // Generate DC PDM stream
    task generate_pdm_dc(input real dc_value, input int num_output_samples);
        int i;
        
        for (i = 0; i < num_output_samples * FINAL_DECIMATION; i++) begin
            generate_pdm_sample(dc_value);
        end
    endtask

    // --- 7. Instantiate the Device Under Test (DUT) ---
    karaoke_top DUT (
        .pdm_data(pdm_data),
        .reset_n(reset_n),
        .clk(clk_1m536mhz),     
        .audio_sample(audio_sample),
        .audio_valid(audio_valid),
        .sck(sck),
        .sdo(sdo),
        .cs(cs)
    );


    // --- 8. Output Sample Collection (16 kHz Domain) ---

    // Collect valid PCM samples for later analysis
    always @(posedge clk_1m536mhz) begin
        if (audio_valid) begin
            // Use index access and check bounds since 'output_samples' is now a fixed array
            if (output_count < $size(output_samples)) begin
                output_samples[output_count] = q15_to_real(audio_sample);
                output_count++;
                $display("Time=%0t: PCM Sample #%0d Valid. Value=0x%h (%.4f real)",
                         $time, output_count, audio_sample, q15_to_real(audio_sample));
            end else begin
                $error("Output sample array capacity exceeded!");
            end
        end
    end
    
    // --- 9. Test Cases (DC and Sine Wave) ---

    // Test 1: DC Input Test
    task test_dc(input real dc_value, input string name);
        real sum, avg, error;
        int i;
        
        $display("\n-------------------------------------------------");
        $display("Test: DC Input (%s, %.2f)", name, dc_value);
        $display("-------------------------------------------------");
        
        output_count = 0; // Reset sample count instead of deleting queue
        sigma_delta_integrator = 0.0;
        
        // Generate stimulus for 150 output samples
        generate_pdm_dc(dc_value, 150);
        
        // Skip initial transient samples (e.g., first 50)
        sum = 0.0;
        if (output_count > 50) begin // Use output_count as the effective size
            for (i = 50; i < output_count; i++) begin
                sum += output_samples[i];
            end
            avg = sum / (output_count - 50);
            error = avg - dc_value;
            
            $display("  Input DC: %.4f", dc_value);
            $display("  Samples collected: %0d (out of %0d total)", output_count, $size(output_samples));
            $display("  Average output (post-transient): %.4f", avg);
            $display("  Error: %.4f", error);
            
            // Tolerance for DC accuracy
            if (abs_real(error) < 0.05) begin
                $display("  PASS: DC gain within tolerance.");
            end else begin
                $display("  FAIL: DC gain error too large.");
            end
        end else begin
            $display("  FAIL: Not enough output samples collected.");
        end
    endtask

    // Test 2: Sine Wave Test
    task test_sine_wave(input real freq);
        real input_power, output_power, gain_db;
        real phase, phase_inc, input_val;
        int i;
        
        $display("\n-------------------------------------------------");
        $display("Test: Sine Wave at %.0f Hz (Expected Passband)", freq);
        $display("-------------------------------------------------");
        
        output_count = 0; // Reset sample count instead of deleting queue
        sigma_delta_integrator = 0.0;
        
        // Generate stimulus for 300 output samples
        generate_pdm_tone(freq, 300);
        
        // Calculate power (skip transient: first 100 samples)
        phase = 0.0;
        phase_inc = freq / FINAL_OUTPUT_RATE;
        input_power = 0.0;
        output_power = 0.0;
        
        if (output_count > 100) begin // Use output_count as the effective size
            for (i = 100; i < output_count; i++) begin
                // The expected input signal at this sample point
                input_val = 0.7 * $sin(2.0 * 3.14159265359 * phase);
                input_power += input_val * input_val;
                output_power += output_samples[i] * output_samples[i];
                phase = phase + phase_inc;
                if (phase >= 1.0) phase = phase - 1.0;
            end
            
            gain_db = 10.0 * $log10(output_power / input_power);
            
            $display("  Frequency: %.0f Hz", freq);
            $display("  Samples collected: %0d (out of %0d total)", output_count, $size(output_samples));
            $display("  Measured Gain: %.2f dB", gain_db);
            
            // Tolerance for gain (0dB +/- 3dB for passband)
            if (gain_db > -3.0 && gain_db < 3.0) begin
                $display("  PASS: Gain within passband tolerance (-3dB to +3dB).");
            end else begin
                $display("  FAIL/WARN: Gain outside expected range.");
            end
        end else begin
            $display("  FAIL: Not enough output samples collected.");
        end
    endtask

    // --- 10. SPI Output Verification ---

    // Monitor SPI transaction (6 MHz domain)
    // Accumulates the SDO output into a 16-bit word and prints the result.
    always @(negedge cs) begin
        if (reset_n && !cs) begin
            // $display("Time=%0t: 📡 SPI CS active (LOW). Starting 16-bit capture.", $time);
            fork
                begin
                    // Use local variables to accumulate the SDO output for this transmission
                    automatic logic [15:0] received_spi_data = 16'h0000;
                    automatic integer i; // Loop counter for 16 bits
                    
                    // Loop 16 times to capture all bits
                    for (i = 0; i < 16; i++) begin
                        // Wait for the falling edge of SCK to sample the data
                        @(negedge sck);
                        
                        // Sample SDO halfway through the SCK low pulse for robust capture
                        # (CLK_6MHZ_PERIOD / 2);
                        
                        // Accumulate the SDO bit into received_spi_data (MSB-first)
                        received_spi_data[15 - i] = sdo;
                    end
                    
                    // Wait for CS to go high to signify end of transmission
                    @(posedge cs);
                    
                    // Report the final accumulated SDO output
                    // $display("Time=%0t: SPI Transfer Complete. Final SDO Output = 0x%h.", $time, received_spi_data);
                    
                    // Minimal check: ensure data isn't all zeros after reset phase
                    if (received_spi_data == 16'h0000 && $time > 50000) begin
                        $warning("Time=%0t: SPI output is 0x0000. Is there input signal?", $time);
                    end
                end
            join_none
        end
    end

    // --- 11. Reset and Main Test Sequence ---
    initial begin
        $display("=================================================");
        $display("KARAOKE TOP Testbench - Full Decimation Chain");
        $display("=================================================\n");
        
        // Initialize
        reset_n = 0;
        pdm_data = 0;
        sigma_delta_integrator = 0.0;
        
        // Wait for clocks to stabilize
        repeat(10) @(posedge clk_48mhz_tb);
        
        // Reset Release
        reset_n = 1;
        $display("Time=%0t: Reset released. Waiting for filter chain to flush.", $time);
        
        // Wait for a few output periods to clear initial transient
        repeat(100) @(posedge clk_1m536mhz);

        // --- Run Tests ---
        test_dc(0.5, "Positive DC"); // Expected DC value: +0.5
        test_dc(-0.5, "Negative DC"); // Expected DC value: -0.5
        test_dc(0.0, "Zero DC");     // Expected DC value: 0.0

        // Sine wave tests (16kHz Nyquist is 8kHz)
        test_sine_wave(500.0);  // Low frequency (in passband)
        test_sine_wave(4000.0); // Mid-range frequency (still in passband)
        // test_sine_wave(9000.0); // Would be stopband for 16kHz Fs, skip for a quick sanity test

        // End simulation
        $display("\n=================================================");
        $display("All KARAOKE TOP tests completed!");
        $display("=================================================");
        $finish;
    end

    // --- 12. Simulation Control ---
    /*
	initial begin
        // Run the simulation for the defined length (watchdog timer)
        #(SIM_LENGTH) $display("Time=%0t: ERROR: Simulation timeout!", $time);
        $finish;
    end*/

endmodule